/**
 * AzurePOC | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Pokemon } from '../model/models';
import { Configuration } from '../configuration';

export interface AzurePOCServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   */
  availablePokemonImages(
    extraHttpRequestParams?: any
  ): Observable<Array<string>>;

  /**
   *
   *
   */
  getPokemon(extraHttpRequestParams?: any): Observable<Array<Pokemon>>;

  /**
   *
   *
   * @param name
   */
  getPokemonImage(name: string, extraHttpRequestParams?: any): Observable<{}>;
}
